config/routes.rb
Rails.application.routes.draw do
  # Devise routes with custom controllers
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    registrations: 'users/registrations'
  }

  # Routes for authenticated users
  authenticated :user do
    root to: 'users/dash_boards#index', as: :authenticated_root
    # Updated routes to use the users namespace
    get 'dash_boards', to: 'users/dash_boards#index', as: :users_dash_boards
    delete 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  # Other routes
  # Removed duplicate and unnecessary route for dash_boards
  # resources :dash_boards, only: [:index]

  # Letter Opener Web for development environment
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Devise scope for unauthenticated users
  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  # Users namespace
  namespace :users do
    resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy]
    # Corrected users_dash_boards route within users namespace
    resources :dash_boards, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: { maximum: 10 }
    validates :content, presence: true
  
    # Active Storageを使用して画像ファイルを扱うための関連を追加する
    has_one_attached :image_file
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Deviseのモジュール
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  # バリデーションの追加
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(resource)
    users_dash_boards_path # ログイン後のリダイレクト先
  end

  def after_sign_up_path_for(resource)
    new_user_session_path
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
      @articles = Article.all
    end
  
    def show
      @article = Article.find(params[:id])
    end
  
    def new
      @article = Article.new
    end
  
    def create
      @article = Article.new(article_params)
      if @article.save
        redirect_to @article
      else
        render :new
      end
    end
  
    def edit
      @article = Article.find(params[:id])
    end
  
    def update
      @article = Article.find(params[:id])
      if @article.update(article_params)
        redirect_to @article
      else
        render :edit
      end
    end
  
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to articles_path
    end
  
    private
  
    def article_params
      params.require(:article).permit(:title, :content, :image_url)
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
  end

app/controllers/users/articles_controller.rb
# app/controllers/users/articles_controller.rb
module Users
  class ArticlesController < ApplicationController
    before_action :authenticate_user! # ログインユーザーのみを許可する

      def index
        @articles = Article.all
      end
    
      def show
        @article = Article.find(params[:id])
      end
    
      def new
        @article = Article.new
      end
    
      def create
        @article = Article.new(article_params)
        if @article.save
          redirect_to users_article_path(@article), notice: 'Article was successfully created.'
        else
          render :new
        end
      end
      
    
      def edit
        @article = Article.find(params[:id])
      end
    
      def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
          redirect_to users_article_path(@article)
        else
          render :edit
        end
      end

      def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to users_articles_path, notice: 'Article was successfully destroyed.'
      end
      
      
    
      private
    
      def article_params
        params.require(:article).permit(:title, :content, :image_url, :image_file)
      end
    end
  end
  

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
    before_action :set_default_format
  
    def create
      self.resource = resource_class.send_confirmation_instructions(resource_params)
      yield resource if block_given?
  
      respond_to do |format|
        if successfully_sent?(resource)
          format.html { redirect_to after_resending_confirmation_instructions_path_for(resource_name), notice: '確認指示を再送信しました。' }
          format.json { render json: { message: '確認指示を再送信しました。' }, status: :ok }
        else
          format.html { render :new }
          format.json { render json: resource.errors, status: :unprocessable_entity }
        end
      end
    end
  
    private
  
    def set_default_format
      request.format = :html if params[:format].nil? || !%w[html json].include?(params[:format])
    end
  end
  

app/controllers/users/dash_boards_controller.rb
# app/controllers/users/dash_boards_controller.rb

class Users::DashBoardsController < ApplicationController
  before_action :authenticate_user!

  def index
    # ダッシュボードのコードをここに追加する
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    protected
  
    def after_update_path_for(resource)
      dash_boards_path
    end
  end
  

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
    # ログアウト後のリダイレクト先を設定
    def after_sign_out_path_for(resource_or_scope)
      new_user_session_path
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    def edit
      @user = current_user
    end
  
    def update
      @user = current_user
      if @user.update(user_params)
        redirect_to root_path, notice: 'Profile updated successfully'
      else
        render :edit
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/home/index.html.erb
<h1>Hello World test</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JITM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap 5 CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Bootstrap 5 JavaScript Bundle -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/js/bootstrap.bundle.min.js"></script>
  </head>
  <body>
    <div class="container">
      <div class="row justify-content-center align-items-center" style="min-height: 50vh;">
        <div class="col-md-6">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/articles/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h1 class="text-center">記事の編集</h1>
      <%= form_for @article, url: users_article_path(@article), method: :patch, html: { class: "form" } do |form| %>
        <div class="form-group">
          <%= form.label :タイトル, class: "control-label" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :内容, class: "control-label" %>
          <%= form.text_area :content, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :画像, class: "control-label" %>

          <%= form.file_field :image_file %>



        </div>
        <div class="text-center mt-3"> <!-- 上下の余白を追加 -->
          <%= form.submit "更新する", class: "btn btn-primary" %>
        </div>
        <% end %>


        <%= link_to '戻る', users_article_path(@article) %>
      </div>
    </div>
  </div>

app/views/users/articles/index.html.erb
<h1 class="text-center">記事一覧</h1>
<div class="container">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-md-6 text-center"> <!-- 幅を指定して中央に配置 -->
      <%= link_to '記事新規作成', new_users_article_path, class: 'btn btn-primary btn-block' %>
    </div>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>詳細表示</th>
      <th>タイトル</th>
      <th>内容</th>
      <th class="text-center">画像</th>
      <th class="text-center">編集・削除</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to '詳細', users_article_path(article), class: 'btn btn-primary' %></td>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td class="text-center">
          <% if article.image_file.attached? %>
            <div class="text-center"> <!-- 画像を中央揃えにする -->
              <%= image_tag url_for(article.image_file), size: "2x" %>
            </div>
          <% end %> <!-- 画像がない場合は何も表示しない -->
        </td>
        <td class="text-center">
          <%= link_to '編集', edit_users_article_path(article), class: 'btn btn-success' %>
          <%= link_to '削除', users_article_path(article), method: :delete, data: { confirm: '本当に削除しますか?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/articles/new.html.erb
<!-- app/views/users/articles/new.html.erb -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center">記事の新規作成</h1>
      <%= form_with(model: @article, url: users_articles_path, local: true, html: { class: "form" }) do |form| %>
        <div class="form-group">
          <%= form.label :title, "タイトル", class: "control-label" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :content, "内容", class: "control-label" %>
          <%= form.text_area :content, class: "form-control" %>
        </div>
画像<br>
<%= form.file_field :image_file %>

        <div class="form-group text-center"><br>
          <%= form.submit "新規作成", class: "btn btn-primary mb-3" %>
        </div>
      <% end %>
      <div class="text-left mt-4">
      <%= link_to '戻る', users_articles_path %>
    </div>
    
    </div>
  </div>
</div>

app/views/users/articles/show.html.erb
<h1 class="text-center">記事詳細</h1>

<table class="table">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>内容</th>
      <th class="text-center">画像</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @article.title %></td>
      <td><%= @article.content %></td>
      <td class="text-center">
        <% if @article.image_file.attached? %>
          <%= image_tag url_for(@article.image_file), class: "img-fluid" %>
        <% else %>
          画像なし
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<div class="container text-center">
  <div class="row">
  <div class="col-md-8 offset-md-2">
  <%= link_to '編集', edit_users_article_path(@article), class: "btn btn-success" %>
  <%= link_to '削除', users_article_path(@article), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-danger" %>
</div>
</div>
  <div class="row mt-3">
    <div class="col-md-8 offset-md-2">
      <%= link_to '記事一覧へ戻る', users_articles_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/dash_boards/index.html.erb
<h1 class="mb-4 text-center">Dash Boards</h1>
<p class="mb-4 text-center" style="font-size: 40px;">sample</p>

<div class="actions d-flex flex-column justify-content-center align-items-center">
  <%= link_to '記事一覧', users_articles_path, class: 'btn btn-primary mb-2 w-50' %>
  <%= link_to '編集', edit_user_registration_path, class: 'btn btn-primary mb-2 w-50' %>
  <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { confirm: '本当にログアウトしますか？' }, class: 'btn btn-warning mb-2 w-50' %>
</div>